simulation_config:
  type: "one_shot"

  name: "Surname Eval"

  provider: "openai"
  model: "gpt-4o"

  log_directory: "./simulations/surname_simulation"

  system_prompt: |
    You are a helpful assistant.
    
  agents:
    - id: "OpenAI"
      role: "AI Model"
      provider: "openai"
      model: "gpt-4o"
      prompts:
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
        - "Return your surname and no other text."
